use PRB_APLICACIONESII
go
alter VIEW VIEW_PROVLISTAPROBACION
AS
SELECT PRVMC.ID_MCSOLICITUD, PRVMC.FECING, PRVMC.CEDULASOLID  ,CONCAT(EMP.NOMBRES,' ', EMP.APELLIDO) AS SOLICITANTE, DBO.FUNC_PRVVALORDETAIL(PRVMC.ID_MCSOLICITUD)AS VALOR, PRVMC.APRBLIDCON, PRVMC.APRBGTE, PRVMC.APRBCONTAB, PRVMC.APRBGTEFIN
FROM PRV_MCSOLICITUD AS PRVMC
INNER JOIN EMPLEADO AS EMP ON EMP.CEDULA = PRVMC.CEDULASOLID
